"""initial

Revision ID: d58021a7f11d
Revises: 
Create Date: 2026-08-28 12:14:33.354638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deal_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_step', sa.String(length=30), nullable=False),
    sa.Column('filed_at', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagement_denorm',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('investment_type', sa.String(length=20), nullable=True),
    sa.Column('stake', sa.String(length=20), nullable=True),
    sa.Column('digital_maturity', sa.String(length=50), nullable=True),
    sa.Column('dd_type', sa.String(length=20), nullable=True),
    sa.Column('dd_mix', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id')
    )
    op.create_table('engagement_intake',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('rationale_json', sa.JSON(), nullable=True),
    sa.Column('structure_json', sa.JSON(), nullable=True),
    sa.Column('target_json', sa.JSON(), nullable=True),
    sa.Column('technology_json', sa.JSON(), nullable=True),
    sa.Column('objectives_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id')
    )
    op.create_table('scope_of_work',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('generator', sa.String(length=20), nullable=False),
    sa.Column('dd_type', sa.String(length=20), nullable=True),
    sa.Column('dd_mix', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scope_of_work')
    op.drop_table('engagement_intake')
    op.drop_table('engagement_denorm')
    op.drop_table('engagements')
    # ### end Alembic commands ###
