import type { ResearchFinding, ResearchPayload, ResearchSource } from "@/types/research";
import { RESEARCH_CATEGORY_LABELS } from "@/types/research";

/** The disclaimer leads. It is the first thing a reader sees, not a footnote, because
 *  the failure mode of AI research is confident, well-formatted, plausible wrongness. */
function Disclaimer({ text }: { text: string }) {
  return (
    <div
      role="note"
      className="mb-8 rounded-xl border border-redline/40 bg-redline-tint px-4 py-3"
    >
      <p className="font-sans text-[13px] leading-[1.55] text-text">
        <span className="font-semibold">AI-generated research.</span>{" "}
        {text.replace(/^AI-generated research\s*—\s*/i, "")}
      </p>
    </div>
  );
}

function SourceLink({ source }: { source: ResearchSource }) {
  return (
    <a
      href={source.url}
      target="_blank"
      rel="noopener noreferrer"
      className="font-sans text-[13px] text-steel underline underline-offset-2 hover:text-kpmg-blue"
    >
      {source.title}
    </a>
  );
}

function Finding({
  finding,
  sources,
}: {
  finding: ResearchFinding;
  sources: Map<string, ResearchSource>;
}) {
  const cited = finding.source_ids
    .map((id) => sources.get(id))
    .filter((s): s is ResearchSource => Boolean(s));

  return (
    <li className="border-t border-line py-4 first:border-t-0">
      <div className="mb-1 flex flex-wrap items-baseline gap-2">
        <h4 className="font-sans text-[14.5px] font-semibold text-text">{finding.topic}</h4>
        <span className="rounded-full bg-paper-3 px-2 py-0.5 font-sans text-[10.5px] font-medium text-muted uppercase">
          {RESEARCH_CATEGORY_LABELS[finding.category] ?? finding.category}
        </span>
      </div>
      <p className="max-w-[72ch] font-sans text-[14px] leading-[1.6] text-text">{finding.detail}</p>
      {cited.length > 0 && (
        <p className="mt-1.5 flex flex-wrap gap-x-3 gap-y-1">
          {cited.map((source) => (
            <SourceLink key={source.id} source={source} />
          ))}
        </p>
      )}
    </li>
  );
}

export function ResearchSummary({ research }: { research: ResearchPayload }) {
  // Findings cite sources by id; resolving here means a dangling id renders nothing
  // rather than an empty link.
  const sources = new Map(research.sources.map((s) => [s.id, s]));

  return (
    <article>
      <Disclaimer text={research.disclaimer} />

      <section className="mb-8">
        <h2 className="mb-3 font-display text-lg font-semibold text-text">Summary</h2>
        <p className="max-w-[72ch] font-sans text-[15px] leading-[1.65] text-text">
          {research.summary}
        </p>
      </section>

      {research.findings.length > 0 && (
        <section className="mb-8">
          <h2 className="mb-1 font-display text-lg font-semibold text-text">What the sources say</h2>
          <p className="mb-3 font-sans text-[13px] text-muted">
            Each point links to the source it came from. Check it before relying on it.
          </p>
          <ul className="rounded-xl border border-line bg-paper-2 px-4">
            {research.findings.map((finding) => (
              <Finding key={finding.topic} finding={finding} sources={sources} />
            ))}
          </ul>
        </section>
      )}

      {research.sources.length > 0 && (
        <section className="mb-8">
          <h2 className="mb-3 font-display text-lg font-semibold text-text">
            Sources ({research.sources.length})
          </h2>
          <ol className="space-y-1.5">
            {research.sources.map((source) => (
              <li key={source.id} className="font-sans text-[13.5px]">
                <span className="mr-2 font-sans text-[12px] text-muted-2">{source.id}</span>
                <SourceLink source={source} />
                {source.publisher && (
                  <span className="ml-2 font-sans text-[12.5px] text-muted-2">
                    {source.publisher}
                  </span>
                )}
              </li>
            ))}
          </ol>
        </section>
      )}

      <footer className="border-t border-line pt-4 font-sans text-[12px] text-muted-2">
        Researched {new Date(research.researched_at).toLocaleString()} · generated by{" "}
        {research.generator}
      </footer>
    </article>
  );
}
