"""Excel export of the IRL — the artefact that actually goes to the target.

Exactly three columns, as specified: **Function | Question | Response**. Response is
deliberately empty; that is the column the client fills in and sends back.

Any responses already typed in the app are written into the Response column, so the
workbook round-trips rather than discarding work.

`xlsxwriter` is already in the environment (python-pptx depends on it) and is pinned
explicitly in requirements.txt.
"""

import io
import re
from typing import Any

import xlsxwriter

from app.schemas.irl import IrlPayload

SHEET_NAME = "Initial Request List"

# Wide enough to read without resizing, narrow enough to print. Response gets the most
# room because that is where the target writes.
_COL_FUNCTION = 26
_COL_QUESTION = 82
_COL_RESPONSE = 62

_ROW_HEIGHT = 34


def render_xlsx(payload: IrlPayload, responses: dict[str, str] | None = None) -> bytes:
    """The IRL as a .xlsx workbook, returned as bytes."""
    answers = responses or {}
    buf = io.BytesIO()

    workbook = xlsxwriter.Workbook(buf, {"in_memory": True, "constant_memory": False})
    workbook.set_properties(
        {
            "title": f"Initial Request List — {payload.company_name or 'Target'}",
            "subject": "Technology due diligence",
            "comments": "Generated by the KPMG Tech Diligence Tool.",
        }
    )

    header = workbook.add_format(
        {
            "bold": True,
            "font_color": "#FFFFFF",
            "bg_color": "#00338D",
            "align": "left",
            "valign": "vcenter",
            "border": 1,
            "border_color": "#DDE3ED",
        }
    )
    cell = workbook.add_format(
        {"valign": "top", "text_wrap": True, "border": 1, "border_color": "#DDE3ED"}
    )
    function_cell = workbook.add_format(
        {
            "valign": "top",
            "text_wrap": True,
            "bold": True,
            "border": 1,
            "border_color": "#DDE3ED",
        }
    )
    # Unlocked and tinted so it reads as "your turn" when the target opens the file.
    response_cell = workbook.add_format(
        {
            "valign": "top",
            "text_wrap": True,
            "border": 1,
            "border_color": "#DDE3ED",
            "bg_color": "#F4F6FA",
        }
    )

    sheet = workbook.add_worksheet(SHEET_NAME)
    sheet.set_column(0, 0, _COL_FUNCTION)
    sheet.set_column(1, 1, _COL_QUESTION)
    sheet.set_column(2, 2, _COL_RESPONSE)

    sheet.write(0, 0, "Function", header)
    sheet.write(0, 1, "Question", header)
    sheet.write(0, 2, "Response", header)

    # Header stays visible while the target scrolls a long list, and the filter lets
    # each function's owner see only their own rows.
    sheet.freeze_panes(1, 0)

    # Grouped by function so the workbook matches the on-screen order, and so one
    # function's rows sit together for whoever it is forwarded to.
    ordered = _ordered_questions(payload)

    for index, question in enumerate(ordered, start=1):
        sheet.set_row(index, _ROW_HEIGHT)
        sheet.write(index, 0, question.function, function_cell)
        sheet.write(index, 1, question.question, cell)
        sheet.write(index, 2, answers.get(question.id, ""), response_cell)

    last_row = max(1, len(ordered))
    sheet.autofilter(0, 0, last_row, 2)

    workbook.close()
    return buf.getvalue()


def _ordered_questions(payload: IrlPayload) -> list[Any]:
    """Questions in function order, falling back to payload order.

    `functions` carries the resolved grouping; if it is somehow absent or incomplete,
    every question must still be exported — losing a request silently would be worse
    than an imperfect order.
    """
    by_id = {q.id: q for q in payload.questions}
    ordered: list[Any] = []
    seen: set[str] = set()

    for function in payload.functions:
        for question_id in function.question_ids:
            question = by_id.get(question_id)
            if question is not None and question_id not in seen:
                ordered.append(question)
                seen.add(question_id)

    for question in payload.questions:
        if question.id not in seen:
            ordered.append(question)
            seen.add(question.id)

    return ordered


def render_xlsx_from_payload(
    payload: dict[str, Any], responses: dict[str, str] | None = None
) -> bytes:
    """Render a stored payload. Only schema v1 exists so far."""
    if payload.get("schema_version") != 1:
        raise ValueError("Only schema v1 request lists can be exported to Excel")
    return render_xlsx(IrlPayload.model_validate(payload), responses)


def xlsx_filename(deal_name: str, version: int) -> str:
    """`project-redline-irl-v2.xlsx`, matching the PDF and PPT naming."""
    slug = re.sub(r"[^a-z0-9]+", "-", deal_name.lower()).strip("-")
    return f"{slug}-irl-v{version}.xlsx" if slug else f"irl-v{version}.xlsx"
