import { Badge } from "@/components/ui/badge";

/**
 * Shows the forming Enterprise/Product leaning. Phase 1 has no derivation
 * engine (CLAUDE.md §9), so this always renders the placeholder verdict,
 * visibly marked as such. TODO(phase-2): replace with the real signal panel
 * once ScopeGenerator has a non-placeholder implementation.
 */
export function SignalPanel() {
  return (
    <aside className="rounded-[3px] border border-line-strong bg-paper-2 p-5">
      <div className="mb-3 flex items-center justify-between">
        <h3 className="font-mono text-[11px] tracking-[0.08em] text-muted uppercase">Enterprise / Product signal</h3>
        <Badge tone="neutral">Preliminary</Badge>
      </div>
      <p className="font-serif text-[14px] leading-[1.55] text-muted italic">
        The signal engine is not yet enabled. Once filed, this engagement&apos;s scope will be generated by a
        deterministic placeholder — not a real Enterprise/Product classification.
      </p>
    </aside>
  );
}
